import type { ApplicabilityRule, ContextDefinition } from "./types";

// Product decisions delegated by the user on 2026-09-12. This is an overlay;
// it is not a quotation from, or a mutation of, the signed master package.
export const APPLICABILITY_VERSION = "1.0.0";
export const INTEGRATION_VERSION = "1.4.0-applicability.1";

export const contextDefinitions = {
  PREGNANCY_POSSIBLE: { label: "A possibilidade de gravidez é pertinente à realidade de vocês?", help: "Considere se uma relação entre vocês pode resultar em gravidez. Não informe exames, diagnósticos ou métodos utilizados." },
  PREGNANCY_POSTPARTUM_RELEVANT: { label: "Gravidez ou pós-parto, atuais ou futuros, são pertinentes à realidade de vocês?", help: "Inclua a possibilidade futura desse período, conforme a regra original. Não é necessário informar detalhes de saúde." },
  RESPONSABILIDADE_PARENTAL: { label: "Você exerce responsabilidade parental?", help: "Considere cuidado e educação de filhos, inclusive adotivos, enteados ou sob sua responsabilidade. Não depende de vínculo biológico ou de morar na mesma casa; não informe nomes nem idades." },
  HAS_CHILDREN_OR_DEPENDENTS: { label: "Há filhos ou dependentes envolvidos na sua vida familiar?", help: "Inclua dependentes envolvidos na relação familiar, mesmo sem responsabilidade parental formal ou residência conjunta. Não informe dados deles." },
  USES_INTOXICATING_SUBSTANCE: { label: "Houve consumo de álcool ou outra substância capaz de produzir intoxicação no período de referência?", help: "O contexto é o consumo, mesmo sem embriaguez. Não informe qual substância, quantidade, prescrição ou diagnóstico." },
  EX_CONTACT_RELEVANT: { label: "Contato com ex-relacionamento ou antigo interesse é uma situação presente ou concretamente prevista na sua realidade?", help: "Inclua contato necessário por filhos ou trabalho. Não é preciso identificar ninguém; ter tido um relacionamento no passado, sozinho, não obriga a responder." },
  PERSONAL_PHONE_USE: { label: "Você usa um celular pessoal no período de referência?", help: "A resposta não autoriza acesso ao aparelho, às mensagens ou às senhas." },
  DIGITAL_CONVERSATIONS: { label: "Conversas por mensagens ou redes sociais fazem parte da sua realidade?", help: "Não é necessário declarar interesse por alguém nem identificar interlocutores. A pergunta trata dos limites dessas conversas." },
  SOCIAL_PUBLISHING: { label: "Você publica ou considera publicar conteúdo sobre o casamento em redes sociais?", help: "Inclua publicações feitas por outra pessoa a seu pedido. Não publicar nem considerar publicações torna este tema inaplicável." },
  SENSITIVE_FRIENDSHIP: { label: "Há uma amizade próxima na sua realidade para a qual faz sentido avaliar limites afetivos ou sexuais?", help: "Não informe identidade, gênero ou detalhes da amizade. Isso não declara envolvimento nem quebra de confiança." },
  SHARED_DOMESTIC_RESPONSIBILITIES: { label: "Há tarefas domésticas pelas quais vocês têm responsabilidade?", help: "Inclua tarefas realizadas por terceiros ou distribuídas entre residências. Morar separado não implica, por si só, ausência de responsabilidades." },
  PROFESSIONAL_ACTIVITY: { label: "Você exerce trabalho ou atividade profissional no período de referência?", help: "Inclua trabalho formal, informal, autônomo e atividade profissional não remunerada. A renda não determina a aplicabilidade." },
  SEXUAL_INITIATIVE_IN_PERIOD: { label: "Houve alguma iniciativa ou aproximação sexual entre vocês nos últimos 90 dias?", help: "Inclua aproximação que não terminou em relação sexual ou que foi recusada. Este contexto não indica consentimento." },
  PARTNER_DECLINED_IN_PERIOD: { label: "Nos últimos 90 dias, houve situação em que você desejou intimidade e seu cônjuge não desejou naquele momento?", help: "Considere qualquer indicação de que não queria, inclusive sem uma recusa verbal. Não informe detalhes do episódio." },
  DESIRE_DIFFERENCE_IN_PERIOD: { label: "Você percebeu diferença de desejo sexual entre vocês no período de referência?", help: "Inclua ausência de desejo de uma pessoa. Não é necessário que tenha havido relação sexual." },
  SEXUAL_CONTACT_IN_PERIOD: { label: "Houve alguma forma de intimidade sexual entre vocês nos últimos 90 dias?", help: "Considere também contato indesejado. Informar esse contexto não declara consentimento nem autoriza nova aproximação." },
  INTIMACY_DISCOMFORT_IN_PERIOD: { label: "Você sentiu dor, desconforto físico ou emocional durante alguma forma de intimidade no período de referência?", help: "Não informe diagnóstico, prática ou detalhes. As perguntas de segurança continuam disponíveis independentemente deste contexto." },
  SEXUAL_DIFFICULTY_RELEVANT: { label: "Você percebe alguma dificuldade física, emocional ou funcional afetando sua vida sexual no período de referência?", help: "Considere dificuldade atual ou vivenciada no período, sem precisar de diagnóstico ou informar sua natureza." },
  INTIMACY_AFTER_CONFLICT: { label: "No período de referência, você considerou ou viveu intimidade enquanto uma discussão ou mágoa ainda não estava resolvida?", help: "A intimidade não precisa ter ocorrido. Não é necessário descrever o conflito." },
  UNSPOKEN_INTIMATE_PREFERENCE: { label: "Há desejo, fantasia ou preferência íntima que você ainda não conversou claramente com seu cônjuge?", help: "Informe somente se o contexto existe. Nenhum conteúdo desse desejo será solicitado neste campo." },
  TEMPORARY_SEXUAL_LIMITATION: { label: "Alguma circunstância impediu temporariamente a relação sexual no período de referência?", help: "Inclua saúde, recuperação, tratamento, cansaço extremo ou outra limitação. Não solicite confirmação do cônjuge nem informe a causa." },
  SEXUAL_CHANGE_RELEVANT: { label: "Mudanças relacionadas a idade, hormônios, medicamentos ou saúde afetaram o desejo ou a resposta sexual de algum de vocês?", help: "Considere mudanças atuais ou do período de referência, sem inferir pela idade e sem informar medicamentos ou diagnósticos." },
  SEXUAL_DISTANCE_RELEVANT: { label: "Há ou houve no período de referência um afastamento sexual prolongado depois de uma fase de intimidade entre vocês?", help: "Considere o que é prolongado na sua experiência, sem um número imposto de dias. Responder sim não significa desejar ou consentir com a retomada." },
  OWN_DECLINE_IN_PERIOD: { label: "Você recusou alguma aproximação íntima do seu cônjuge no período de referência?", help: "Inclua indicação verbal ou não verbal de que não desejava. A recusa não gera obrigação de retomar a intimidade." },
  PHYSICAL_DISTANCE_IN_PERIOD: { label: "Vocês passaram alguns dias fisicamente separados no período de referência?", help: "Inclua viagem, trabalho ou outra circunstância. Não informe motivo, local ou itinerário." },
  OWN_FAMILY_RELEVANT: { label: "Sua família de origem tem convivência ou influência na sua vida conjugal atual?", help: "Inclua pessoas que exerceram esse papel familiar. Ausência de contato não impede responder se ainda houver influência relevante; não é necessário retomar contato." },
  FAMILY_CONTACT_RELEVANT: { label: "A convivência com alguma das famílias de origem é presente ou concretamente prevista na vida de vocês?", help: "Considere a família de qualquer um dos dois e pessoas que exerceram esse papel. Não é necessário reatar vínculos rompidos." },
  FAMILY_SUPPORT_RELEVANT: { label: "Apoio financeiro, cuidado ou acolhimento de familiares é uma situação presente ou concretamente possível para vocês?", help: "Não exige pedido atual de ajuda nem concordância em ajudar. Não informe nome, renda, doença ou condição do familiar." },
  TWO_FAMILIES_RELEVANT: { label: "As duas famílias de origem estão presentes nas relações ou responsabilidades atuais de vocês?", help: "Só é possível comparar a distribuição entre duas famílias quando ambas fazem parte do contexto. Considere vínculos e responsabilidades mesmo à distância." },
  CHRISTIAN_FAITH_PERSONAL: { label: "A fé cristã faz parte da sua vivência pessoal?", help: "A resposta é individual; a fé do cônjuge não define a sua. Não ter essa vivência torna a pergunta inaplicável, sem presumir uma resposta sobre sua fé." },
  SHARED_PRAYER_RELEVANT: { label: "Orar em casal é uma prática que você vive ou vê valor em construir voluntariamente?", help: "Não praticar atualmente é diferente de não desejar essa prática. Nenhuma resposta autoriza imposição religiosa." },
  SHARED_BIBLE_RELEVANT: { label: "Você deseja ou aceita voluntariamente ter leitura bíblica, devocional ou estudo cristão em conjunto?", help: "As três alternativas escolhem uma frequência. Se você não deseja essa prática, não será obrigado a escolher uma frequência mínima." },
  CHRISTIAN_COMMUNITY_RELEVANT: { label: "Participar de igreja ou comunidade cristã em casal é algo que você deseja ou aceita voluntariamente?", help: "Não exige presença atual, filiação a uma igreja ou concordância do cônjuge." },
  FAITH_DIFFERENCES_RELEVANT: { label: "Convicções ou práticas de fé fazem parte das diferenças ou decisões que vocês precisam considerar?", help: "Inclua diferença entre fé e ausência de fé. Não depende de ambos professarem a mesma religião. A pergunta sobre controle religioso não depende deste campo." },
  RELIGIOUS_DONATIONS_RELEVANT: { label: "Doações religiosas que afetam o orçamento familiar são realizadas ou consideradas por você?", help: "Não é necessário doar atualmente nem aceitar valor mínimo. Renda zero não torna o tema automaticamente inaplicável." },
  RELIGIOUS_SERVICE_IN_PERIOD: { label: "Você dedica tempo a atividades de igreja, ministério ou serviço religioso no período de referência?", help: "Inclua serviço voluntário. Não informe instituição, função ou crença do cônjuge." },
  SHARED_SPIRITUAL_REVIEW_RELEVANT: { label: "Você deseja ou aceita voluntariamente revisar a vida espiritual em casal?", help: "As três alternativas definem periodicidade. Ausência de interesse nessa prática não será convertida em uma frequência obrigatória." },
  PARTNER_ILLNESS_IN_PERIOD: { label: "Seu cônjuge esteve doente ou temporariamente incapacitado no período de referência?", help: "Inclua situação ainda em curso. Não informe diagnóstico, tratamento ou dados de saúde do cônjuge." },
  EMOTIONAL_DIFFICULTY_RELEVANT: { label: "Você percebe dificuldade emocional afetando significativamente sua rotina ou relacionamento no período de referência?", help: "Não exige diagnóstico. Informe apenas se esse contexto faz parte da sua experiência, sem descrever sintomas." },
  HEALTH_IMPACT_RELEVANT: { label: "Há ou houve questão de saúde sua com impacto direto na rotina, finanças ou responsabilidades do casal no período de referência?", help: "Informe somente a existência do contexto. Isso não autoriza compartilhar sua informação de saúde." },
  TIME_INTENSIVE_HOBBY: { label: "Você tem hobby ou atividade pessoal que ocupa muitas horas da semana?", help: "Considere sua rotina no período de referência. Não há um limite de horas criado pelo sistema, e o contexto não comprova prejuízo." },
  FAMILY_EXPANSION_RELEVANT: { label: "Ter filhos ou ampliar a família é um tema pertinente ao projeto de vida de vocês?", help: "Inclua dúvidas, divergência ou a posição de não querer filhos. Não depende de fertilidade, idade ou já ter filhos; considere também outras formas de ampliar a família. Marque não somente se o tema não fizer parte da realidade nem do projeto de vida de vocês." },
  DIGITAL_ENTERTAINMENT_IN_PERIOD: { label: "Você usou jogos eletrônicos, streaming ou entretenimento digital nos últimos 90 dias?", help: "Inclua uso ocasional. Não informe aplicativos, histórico ou tempo de uso." },
  NONWORK_DIGITAL_USE: { label: "Você usou celular ou redes sociais fora das necessidades de trabalho nos últimos 90 dias?", help: "Inclua uso ocasional. Ter um aparelho exclusivamente profissional não basta para esta pergunta." },
  HABIT_REDUCTION_ATTEMPT: { label: "Você tentou reduzir ou parar um hábito prejudicial no período de referência, ou ainda vive as consequências de uma tentativa relevante?", help: "Não é necessário identificar o hábito. A resposta não é diagnóstico e não cria um evento de recaída." },
  UNRESOLVED_REPEATED_PROBLEM: { label: "Há um problema importante atual que vocês já conversaram diversas vezes sem conseguir resolver?", help: "Não informe o tema nem o conteúdo das conversas. A existência desse contexto não dispara um protocolo por si só." },
  KNOWN_TRUST_BREACH: { label: "Há histórico relevante de quebra grave de confiança já conhecido pelos dois?", help: "Não revele conteúdo desconhecido pelo cônjuge. Este contexto permanece privado e não será usado como aviso ao outro." },
  REBUILDING_CHOSEN: { label: "Vocês decidiram voluntariamente tentar reconstruir o relacionamento após essa quebra de confiança?", help: "Informe sua percepção dessa decisão, sem presumir concordância do outro. A abordagem ainda depende de revisão privada de segurança; este campo não a substitui." },
  PARTNER_CHANGE_ATTEMPT: { label: "Você percebe uma tentativa concreta atual ou recente do seu cônjuge de corrigir um comportamento que causava conflito?", help: "Não é necessário considerar o problema resolvido, perdoar ou retomar confiança. Não informe o comportamento." },
  REGRESSION_IN_PERIOD: { label: "Uma melhora alcançada começou a desaparecer ou um problema antigo voltou no período de referência?", help: "Não informe o problema. Este contexto não define gravidade, culpa ou prazo de intervenção." },
  PARTNER_LOSS_RELEVANT: { label: "Seu cônjuge atravessa ou atravessou no período de referência uma perda ou sofrimento importante?", help: "Inclua luto ainda em curso, mesmo iniciado antes do período. Não há prazo imposto de recuperação e não é necessário informar a perda." },
  CONCRETE_HARM_RELEVANT: { label: "Alguma atitude sua produziu prejuízo concreto ao cônjuge ou à família no período de referência, ou deixou consequências ainda presentes?", help: "Não informe valores nem detalhes. O contexto não comprova dívida nem autoriza cobrança." },
  FORGIVENESS_RELEVANT: { label: "Há erro relevante com pedido de perdão cuja forma de tratamento ainda faz parte da sua experiência atual?", help: "Inclua situações do período de referência ou com efeitos atuais. Não pressupõe aceitar o pedido, perdoar ou restaurar confiança." },
  REPEATED_COMMITMENT_BREACH: { label: "Há compromisso importante descumprido repetidamente apesar de conversas e tentativas de correção?", help: "Considere situação atual ou com efeitos no período de referência. Não informe o compromisso; o campo não comprova recusa injustificada nem autoriza sanção." },
} satisfies Record<string, ContextDefinition>;

type ContextId = keyof typeof contextDefinitions;
type Decision = { questionId: string; rule: ApplicabilityRule; rationale: string };
const always = (questionId: string, rationale: string): Decision => ({ questionId, rule: { always: true }, rationale });
const when = (questionId: string, field: ContextId, rationale: string): Decision => ({ questionId, rule: { context_equals: { [field]: true } }, rationale });

// Every formerly-null rule is explicitly listed. Never default a missing row to true.
export const applicabilityDecisions: Decision[] = [
  always("Q001", "Autoavaliação da reação habitual a problemas; não exige comprovar conflito recente."),
  always("Q002", "Postura sobre decisões que afetam a vida comum, inclusive decisões futuras."),
  always("Q003", "Autoavaliação da reação à irritação; não pressupõe agressão ou episódio recente."),
  always("Q004", "Forma pessoal de demonstrar afeto, inclusive dificuldade de demonstrá-lo."),
  always("Q005", "Preferência de organização da vida familiar, sem exigir filhos ou residência conjunta."),
  always("Q006", "Autoavaliação da reação habitual a reclamações, sem transformar a resposta em registro de evento."),
  always("Q007", "Preferência de vida social; ser reservado ou não frequentar festas não exclui a pergunta."),
  always("Q008", "Autoavaliação de flexibilidade diante de imprevistos, sem exigir uma ocorrência recente."),
  always("Q009", "Preferência sobre como perceber amor; não exige receber atualmente essas demonstrações."),
  always("Q010", "Percepção de reconhecimento, incluindo cuidado e contribuições não financeiras."),
  always("Q011", "Percepção de atenção e conexão; ausência de bons momentos também faz parte da avaliação."),
  always("Q012", "Postura sobre pedidos de ajuda na vida comum; não depende de filhos ou renda."),
  always("Q013", "Autoavaliação da facilidade de reconhecer erros e pedir desculpas."),
  always("Q014", "Preferência de como receber uma conversa difícil; não exige reclamação prévia."),
  always("Q015", "Autoavaliação da postura diante de discordâncias, sem exigir conflito comprovado."),
  always("Q016", "Autoavaliação sobre trazer o passado às conversas; não comprova erros antigos."),
  always("Q017", "Autoavaliação de silêncio e afastamento; não implica autorização para abordagem conjunta."),
  always("Q018", "Preferência sobre necessidades após desculpas; não exige quebra grave de confiança."),
  always("Q019", "Postura sobre buscar apoio e exposição de problemas, mesmo sem apoio externo atual."),
  always("Q020", "Percepção atual de participação nas decisões, sem exigir uma decisão recente específica."),
  always("Q021", "Autoavaliação sobre intenção e impacto, sem pressupor relato de dano."),
  always("Q022", "Percepção de conforto com comentários e brincadeiras; sinais de humilhação não podem ser filtrados por contexto prévio."),
  always("Q023", "Liberdade para abordar assuntos difíceis; não exigir conversa prévia permite relatar evitação por medo."),
  always("Q024", "Postura sobre transparência de informações, sem exigir revelar um segredo."),
  always("Q025", "Autoavaliação de cumprimento de compromissos; não comprova descumprimento específico."),
  always("Q026", "Postura diante de interesse de terceiros; não exige identificar terceiro ou comprovar flerte."),
  when("Q027", "EX_CONTACT_RELEVANT", "Contato com ex ou antigo interesse precisa ser uma situação real ou concretamente prevista; ausência desse contexto não equivale a preferir distância."),
  always("Q028", "Autoavaliação sobre ciúme e insegurança; não exige suspeita de infidelidade."),
  when("Q029", "PERSONAL_PHONE_USE", "As alternativas descrevem relação com celular pessoal; não ter esse uso não é uma posição sobre privacidade."),
  when("Q030", "DIGITAL_CONVERSATIONS", "Exige contexto de comunicação digital, sem exigir existência de interesse afetivo ou sexual."),
  when("Q031", "SOCIAL_PUBLISHING", "Exige publicação atual ou considerada; não possuir rede social não deve ser convertido em concordância com uma regra de postagem."),
  when("Q032", "SENSITIVE_FRIENDSHIP", "Exige amizade próxima para a qual a avaliação de limites faça sentido, sem dedução por gênero ou orientação."),
  always("Q033", "Postura sobre apoio e intimidade emocional, incluindo possibilidade de desenvolver uma troca reservada."),
  always("Q034", "Transparência financeira inclui ausência de renda, dívidas e recursos administrados por terceiros."),
  always("Q035", "Postura sobre crédito e dívida; não exige dívida existente nem autorização de crédito."),
  always("Q036", "Preferência de gastos pessoais; renda zero ou ausência de compras não exclui a avaliação."),
  always("Q037", "Preferência sobre eventual sobra financeira; não exige existir sobra no período."),
  always("Q038", "Preferência de participação na administração financeira, sem dedução pelo nível de renda."),
  always("Q039", "Grau de acompanhamento do orçamento, inclusive pouca participação e ausência de renda própria."),
  always("Q040", "Postura sobre ajuda a terceiros; não exige pedido atual nem disponibilidade financeira."),
  always("Q041", "Preferência de modelo financeiro para todos os participantes, inclusive sem renda própria."),
  always("Q042", "Visão sobre diferença de renda; não exige desigualdade atual nem remuneração dos dois."),
  always("Q043", "Postura diante de eventual crise financeira; a resposta não comprova desemprego ou emergência."),
  when("Q044", "SHARED_DOMESTIC_RESPONSIBILITIES", "Avalia participação real em tarefas domésticas sob responsabilidade do casal, inclusive terceirizadas."),
  always("Q045", "Carga mental inclui organização da vida comum mesmo sem filhos ou domicílio compartilhado."),
  when("Q046", "RESPONSABILIDADE_PARENTAL", "Compila a instrução expressa da própria pergunta: sem responsabilidade parental, não aplicável."),
  when("Q047", "RESPONSABILIDADE_PARENTAL", "Discordância sobre educação exige responsabilidade parental; não se presume pela existência de filhos do outro."),
  when("Q048", "PROFESSIONAL_ACTIVITY", "Avalia equilíbrio da atividade profissional existente; desemprego ou aposentadoria sem atividade não equivalem a limites bem estabelecidos."),
  always("Q049", "Postura sobre oportunidade profissional futura; não exige emprego ou oferta atual."),
  always("Q050", "Postura sobre apoiar desenvolvimento do cônjuge, inclusive projeto futuro."),
  always("Q051", "Compara frequência atual e desejada; frequência zero é uma realidade avaliável e não implica inaplicabilidade."),
  when("Q052", "SEXUAL_INITIATIVE_IN_PERIOD", "Distribuição de iniciativa exige alguma aproximação no período; ausência total não será descrita como equilíbrio."),
  when("Q053", "PARTNER_DECLINED_IN_PERIOD", "A pergunta pede reação real à indisponibilidade do cônjuge; não solicitar reação inventada quando a situação não ocorreu."),
  always("Q054", "Preferência de condições que favorecem disponibilidade; não implica obrigação de desejo ou de contato."),
  always("Q055", "Preferência de reservar momento de reconexão; não exige atividade sexual nem cria consentimento por ocasião."),
  always("Q056", "Percepção de carinho não sexual; ausência de carinho já é contemplada pelas alternativas."),
  always("Q057", "Satisfação com a vida sexual inclui períodos sem relações; não se presume satisfação pela ausência de atividade."),
  always("Q058", "Autoavaliação da liberdade de comunicar preferências e limites, mesmo sem atividade sexual recente."),
  when("Q059", "DESIRE_DIFFERENCE_IN_PERIOD", "Exige diferença de desejo percebida; não infere diferença por gênero, frequência ou resposta do parceiro."),
  always("Q060", "Rastreio de consumo que contempla explicitamente não consumo; não usar filtro prévio de uso."),
  when("Q061", "SEXUAL_CONTACT_IN_PERIOD", "Avaliar reciprocidade durante a intimidade exige experiência no período; não presume consentimento desse contato."),
  when("Q062", "INTIMACY_DISCOMFORT_IN_PERIOD", "Comunicação real de desconforto exige ter vivido esse contexto; sua ausência não é habilidade de comunicar."),
  always("Q063", "Condições de privacidade podem ser avaliadas mesmo quando impedem completamente a intimidade."),
  always("Q064", "A pergunta solicita preferência após a intimidade; não exige episódio recente."),
  always("Q065", "Postura sobre novidades e limites, sem exigir proposta ou prática específica."),
  always("Q066", "Percepção atual de autoimagem e desejo, inclusive quando insegurança provoca evitação."),
  always("Q067", "Contempla explicitamente ausência de masturbação; não filtrar por uso."),
  when("Q068", "SEXUAL_DIFFICULTY_RELEVANT", "Avalia comunicação de dificuldade percebida; não exige diagnóstico nem dedução a partir de outras respostas."),
  when("Q070", "INTIMACY_AFTER_CONFLICT", "Exige experiência ou consideração de intimidade em contexto de mágoa; não exige a realização de contato."),
  always("Q071", "Preferência por espontaneidade ou planejamento, mesmo sem atividade sexual recente."),
  always("Q072", "Percepção de sentir-se desejado; ausência de demonstrações é parte do conteúdo avaliado."),
  always("Q073", "Postura sobre privacidade íntima, incluindo possibilidade de compartilhamento; não exige exposição prévia."),
  when("Q074", "UNSPOKEN_INTIMATE_PREFERENCE", "Exige preferência ainda não conversada; não inventa um desejo nem obriga a revelar seu conteúdo."),
  always("Q075", "Percepção de cuidados e conforto no casamento; dificuldades que inibem a intimidade continuam avaliáveis."),
  when("Q076", "TEMPORARY_SEXUAL_LIMITATION", "Exige período de impedimento; não deduz limitação por sexo, idade, diagnóstico ou frequência."),
  when("Q078", "SEXUAL_CHANGE_RELEVANT", "Exige mudança percebida, sem tornar idade, medicamento ou doença um diagnóstico automático."),
  always("Q079", "Preferência de horário de aproximação; não exige relação sexual nem disponibilidade obrigatória."),
  when("Q080", "SEXUAL_DISTANCE_RELEVANT", "Retomada pressupõe afastamento após intimidade anterior; não impõe duração nem vontade de retomar."),
  always("Q081", "Compreensão de fidelidade e riscos; não depende de atividade sexual atual ou confissão de evento."),
  always("Q082", "Autoavaliação de romantismo; ausência de iniciativas é prevista nas alternativas."),
  when("Q083", "OWN_DECLINE_IN_PERIOD", "Exige aproximação recusada pelo respondente, sem presumir retorno posterior do desejo."),
  when("Q084", "PHYSICAL_DISTANCE_IN_PERIOD", "Avalia comportamento em dias de distância efetivamente vividos; não se inventa viagem ou afastamento."),
  always("Q085", "Preferência sobre registros íntimos inclui recusa de produzi-los; não exige arquivo existente."),
  always("Q086", "Cenário expressamente hipotético sobre comunicação; não exige nem coleta diagnóstico."),
  always("Q087", "Autoavaliação sobre uso de afeto e intimidade; falta legítima de vontade não exclui a pergunta nem comprova punição."),
  when("Q088", "SEXUAL_CONTACT_IN_PERIOD", "Comunicação de experiência íntima exige contato no período; não se presume consentimento nem satisfação."),
  always("Q089", "Postura sobre responsabilidade pela vida íntima; não exige crise comprovada."),
  always("Q090", "Preferência de revisão íntima explicitamente aplicável mesmo sem crise."),
  when("Q091", "OWN_FAMILY_RELEVANT", "Exige vínculo ou influência da família de origem do respondente, sem exigir identificar familiares ou provar conflito."),
  when("Q092", "FAMILY_CONTACT_RELEVANT", "Preferência de convivência familiar exige família presente ou contato concretamente previsto."),
  when("Q093", "FAMILY_CONTACT_RELEVANT", "Preferência sobre visitas de familiares, inclusive futuras, sem obrigar reatar contato."),
  when("Q094", "FAMILY_CONTACT_RELEVANT", "Planejamento de datas com familiares exige contexto de convivência; não impõe celebrações nem contato."),
  when("Q095", "FAMILY_SUPPORT_RELEVANT", "Postura sobre ajuda familiar quando esse apoio é contexto real ou possível; não exige renda disponível."),
  when("Q096", "FAMILY_SUPPORT_RELEVANT", "Planejamento hipotético de cuidado de familiares; não exige familiar doente atualmente."),
  when("Q097", "OWN_FAMILY_RELEVANT", "Postura diante da própria família pressupõe vínculo ou influência atual; não exige declaração prévia de desrespeito."),
  when("Q099", "TWO_FAMILIES_RELEVANT", "Comparação entre duas famílias exige presença das duas no contexto; uma família ausente não equivale a desequilíbrio."),
  when("Q100", "FAMILY_SUPPORT_RELEVANT", "Preferência sobre acolhimento de familiares pressupõe possibilidade concreta, sem exigir pedido atual ou concordância."),
  always("Q101", "Pergunta de segurança disponível sem triagem de medo ou conflito; evitação por medo também é experiência válida."),
  always("Q102", "Rastreio de ameaça com alternativa explícita de ausência; não condicionar a relato anterior."),
  always("Q103", "Rastreio de agressão disponível a todos; não depende de convivência presencial, conflito declarado ou autorização do parceiro."),
  always("Q104", "Rastreio de coerção disponível mesmo sem relação sexual ou recusa verbal; nenhuma ausência de contexto será interpretada como segurança."),
  always("Q105", "Rastreio de intimidação com ausência expressa; não exigir conflito ou dano previamente declarado."),
  always("Q106", "Controle e vigilância podem ocorrer sem celular próprio ou uso voluntário de localização; não filtrar por tecnologia."),
  always("Q107", "Isolamento pode explicar a ausência atual de vínculos; não condicionar a ter amigos ou familiares próximos."),
  always("Q108", "Controle financeiro pode ocorrer sem renda própria; não filtrar por emprego, conta ou recursos."),
  always("Q109", "Restrição de liberdade pode impedir trabalho e estudo; não condicionar a exercê-los."),
  when("Q111", "CHRISTIAN_FAITH_PERSONAL", "As alternativas pressupõem fé cristã pessoal; não atribuir essa fé ao respondente pela religião do parceiro."),
  when("Q112", "SHARED_PRAYER_RELEVANT", "As alternativas incluem valorizar oração compartilhada; não forçar essa posição em quem não a deseja."),
  when("Q113", "SHARED_BIBLE_RELEVANT", "Todas as alternativas propõem frequência de prática cristã; exigir pertinência e vontade individual prévias."),
  when("Q114", "CHRISTIAN_COMMUNITY_RELEVANT", "Todas as alternativas tratam de participação em comunidade cristã; não impor pertencimento ou frequência."),
  when("Q115", "FAITH_DIFFERENCES_RELEVANT", "Diferenças espirituais podem incluir ausência de fé; não exige que os dois sejam cristãos."),
  when("Q116", "RELIGIOUS_DONATIONS_RELEVANT", "As alternativas descrevem modelos de contribuição religiosa; não presume que todos desejem doar."),
  when("Q117", "RELIGIOUS_SERVICE_IN_PERIOD", "Avalia uso real de tempo em serviço religioso; ausência de serviço não equivale a bom equilíbrio ministerial."),
  always("Q119", "Controle religioso pode atingir pessoa sem fé ou prática religiosa; pergunta e complemento privado não recebem filtro de religião."),
  when("Q120", "SHARED_SPIRITUAL_REVIEW_RELEVANT", "Todas as alternativas fixam revisão espiritual; exigir aceitação individual dessa prática sem presumir consenso."),
  always("Q121", "Autoavaliação de cuidado preventivo no período de dois anos da fonte; não depende de doença."),
  always("Q122", "Percepção de sono e descanso, inclusive limitações da rotina e problemas de saúde."),
  always("Q123", "A pergunta já considera atividade compatível com saúde e realidade; limitação não implica falta de compromisso."),
  always("Q124", "Preferência sobre organização alimentar; não exige cozinhar nem realizar refeições conjuntas."),
  when("Q125", "PARTNER_ILLNESS_IN_PERIOD", "Avalia cuidado efetivo em doença ou incapacidade; não inventa experiência nem solicita diagnóstico do parceiro."),
  when("Q126", "EMOTIONAL_DIFFICULTY_RELEVANT", "Avalia pedido de ajuda diante de dificuldade percebida; não presume saúde emocional nem exige diagnóstico."),
  when("Q127", "HEALTH_IMPACT_RELEVANT", "Exige questão de saúde com impacto na vida comum; preserva dados clínicos e privacidade individual."),
  always("Q128", "Postura sobre despesa imprevista de saúde, inclusive planejamento para eventual necessidade."),
  always("Q129", "Modelo expressamente hipotético de redistribuição; não exige limitação de saúde atual."),
  always("Q130", "Preparação para emergências é pertinente sem doença atual; responder não autoriza compartilhar dados de saúde."),
  always("Q131", "Avalia lazer do casal, inclusive ausência de lazer; não depende de dinheiro ou viagem."),
  always("Q132", "Visão de autonomia e lazer individual, mesmo sem hobby atual."),
  always("Q133", "Preferência de estilo de lazer, sem exigir acesso financeiro ou atividade atual."),
  always("Q134", "Preferência de planejamento de viagem futura; não exige férias, renda ou viagem marcada."),
  always("Q135", "Postura sobre orçamento de lazer; falta de recursos não equivale a recusa ou inaplicabilidade."),
  always("Q136", "Postura sobre novidades de lazer, sem exigir proposta já realizada."),
  when("Q137", "TIME_INTENSIVE_HOBBY", "Exige atividade com carga de tempo relevante, sem inferir prejuízo ou fixar limite arbitrário de horas."),
  always("Q138", "Postura sobre descanso, inclusive quando há tarefas pendentes; não exige emprego."),
  always("Q139", "Preferência de significado das datas; não exige celebração, data recente ou gasto."),
  always("Q140", "A própria pergunta condiciona a busca à realidade financeira e familiar; falta de recursos não impede declarar preferência."),
  always("Q141", "Visão de futuro, inclusive ausência de planos; não exige projeto já definido."),
  always("Q142", "Postura sobre projetos pessoais e família, sem depender de trabalho, renda ou filhos."),
  always("Q143", "Prioridade hipotética atual para os próximos anos, sem exigir recursos disponíveis."),
  always("Q144", "Posição diante de mudança hipotética, sem exigir oferta ou autorização para mudar."),
  always("Q145", "Preferência sobre eventual aumento de renda; não exige aumento ocorrido."),
  when("Q146", "FAMILY_EXPANSION_RELEVANT", "Compila a pertinência prévia exigida pela fonte; dúvida, não desejar filhos ou impossibilidade de gravidez não bastam para excluir o tema."),
  always("Q147", "Planejamento da maturidade em qualquer fase adulta; não filtrar por idade ou situação previdenciária."),
  always("Q148", "Postura diante de risco hipotético; não exige patrimônio, investimento ou negócio existente."),
  always("Q149", "Postura sobre adiamento de sonhos, sem exigir um adiamento atual comprovado."),
  always("Q150", "Preferência sobre revisão do projeto de vida, mesmo sem planejamento anterior."),
  always("Q151", "Contempla ausência de consumo; não excluir abstêmios nem condicionar a segurança pela letra."),
  always("Q153", "Contempla ausência de uso; não exigir diagnóstico, consumo declarado ou opinião sobre legalidade para exibir."),
  always("Q154", "Aplica a todos, inclusive quem não aposta; a proibição fixa não depende do consumo nem da letra."),
  always("Q155", "Postura sobre compra não essencial, sem exigir compra efetuada ou renda própria."),
  when("Q156", "DIGITAL_ENTERTAINMENT_IN_PERIOD", "Todas as alternativas pressupõem uso de entretenimento digital; não usar A para quem não utilizou."),
  when("Q157", "NONWORK_DIGITAL_USE", "O enunciado exclui necessidades profissionais; exige algum uso não profissional no período."),
  always("Q158", "Autoavaliação de transparência sobre hábitos; não exige identificar hábito nem revelar conteúdo privado."),
  when("Q159", "HABIT_REDUCTION_ATTEMPT", "Avalia resultado real de tentativa de redução; ausência de tentativa não equivale a conseguir parar."),
  always("Q160", "Disposição diante de evidência de prejuízo, sem exigir diagnóstico ou comprovar um evento."),
  always("Q171", "Visão sobre autonomia social, mesmo sem saídas recentes; ausência de saídas pode decorrer de controle."),
  always("Q172", "Preferência de amizades compartilhadas; a própria alternativa C contempla ausência de convivência."),
  always("Q173", "Postura sobre influência de terceiros, sem exigir identificar amigo ou comprovar opinião recebida."),
  always("Q174", "Preferência sobre receber visitas, inclusive futuras; não exige visita recente ou casa própria."),
  always("Q175", "Postura diante de evento social possível; não exige convite atual ou atividade profissional."),
  always("Q176", "Autoavaliação de postura diante de desgaste; não comprova crise atual nem exclui casais estáveis."),
  always("Q177", "Visão sobre pausas em conflitos; não exige afastamento e não autoriza retomada em situação insegura."),
  always("Q178", "Disposição para ajuda externa, sem exigir tratamento ou crise atual."),
  always("Q179", "Autoavaliação do uso de separação em conflitos, sem exigir intenção ou ameaça prévia."),
  when("Q180", "UNRESOLVED_REPEATED_PROBLEM", "Exige problema atual discutido repetidamente; não se presume falha de resolução a partir de letras."),
  { questionId: "Q181", rule: { context_equals: { KNOWN_TRUST_BREACH: true, REBUILDING_CHOSEN: true }, requires_private_review: "Q181_SAFE_APPROACH" }, rationale: "A fonte exige histórico relevante já conhecido, decisão de reconstruir e abordagem segura. Os dois contextos são privados; a liberação de segurança não pode ser autodeclarada e aguarda PEND-06/PEND-14." },
  when("Q182", "PARTNER_CHANGE_ATTEMPT", "Reconhecimento de melhora exige tentativa concreta percebida; não inventa esforço ou progresso."),
  always("Q183", "Avalia cuidado intencional nos 12 meses da fonte, inclusive sua ausência; não exige filhos ou trabalho."),
  when("Q184", "REGRESSION_IN_PERIOD", "Avalia reação a melhora seguida de regressão; sem essa sequência não se inventa experiência."),
  always("Q185", "Preferência de revisão futura do instrumento; não exige contrato anterior."),
  always("Q186", "Clareza atual de limites, inclusive dificuldade de estabelecê-los; não exigir violência prévia."),
  when("Q187", "PARTNER_LOSS_RELEVANT", "Apoio real em perda ou sofrimento exige esse contexto; luto em curso não tem prazo arbitrário de validade."),
  when("Q188", "CONCRETE_HARM_RELEVANT", "Avalia reparação diante de prejuízo concreto ou consequências atuais; não presume dívida ou culpa de um evento."),
  when("Q189", "FORGIVENESS_RELEVANT", "Avalia experiência de erro e pedido de perdão; não exige perdão concedido ou confiança restaurada."),
  when("Q190", "REPEATED_COMMITMENT_BREACH", "Exige repetição de descumprimento e tentativas de correção; não ativa sanções nem comprova evento por si só."),
  always("Q191", "Autoavaliação de responsabilidade própria, sem atribuição automática de culpa por conflitos ou violência."),
  always("Q192", "Autoavaliação de transformar intenção em ação; não exige promessa formal ou prova de descumprimento."),
  always("Q193", "Postura ao receber feedback posterior, sem exigir reclamação recente."),
  always("Q194", "Estratégia expressamente hipotética para múltiplos problemas; não exige crise atual."),
  always("Q195", "Autoavaliação de princípios e preferências, sem depender de um conflito específico."),
  always("Q196", "Diagnóstico privado da percepção atual do casamento, para todos os participantes."),
  always("Q197", "Diagnóstico privado de esforço percebido, inclusive ausência de esforço dos dois."),
  always("Q198", "Diagnóstico privado da disposição percebida do parceiro, sem compartilhar a resposta ou inferir aceite dele."),
  always("Q199", "Intenção de uso futuro do instrumento, sem exigir contrato pronto."),
  always("Q200", "Disposição individual para o próximo ciclo, inclusive dúvida e resistência; não presume consentimento para avaliação."),
];
