import type { ScorePresentationStatus } from "@/features/admission/domain/score-presentation";

export const GENERAL_PRELIMINARY_ANALYSIS: Record<ScorePresentationStatus, string[]> = {
  PRECISA_MUDAR_COM_URGENCIA: [
    "Esse resultado mostra que existem áreas do relacionamento que precisam melhorar.",
    "A seguir, você vai conhecer a nota de cada área e entender onde estão os principais problemas e o que está fazendo falta na relação.",
    "Quando várias áreas ficam fragilizadas, começa a faltar aquilo que dá força ao casamento: conexão, intimidade, diálogo, parceria, segurança e vontade de construir juntos. E é comum surgir distância, cansaço, frustração e a sensação de que o casamento poderia ser muito melhor.",
    "Mas essa nota mostra como o relacionamento está sendo vivido hoje. Ela não precisa definir o futuro de vocês.",
    "Veja com atenção a análise de cada tópico abaixo.",
    "É ali que você vai perceber quais áreas estão fragilizadas e o que precisa mudar.",
    "Essa análise mostra onde estão os sinais e o que precisa melhorar.",
    "O Método Contrato de Casamento é o próximo passo para aprofundar essas áreas, entender por que isso está acontecendo e descobrir o que cada um precisa fazer diferente.",
    "No método completo, vocês irão responder, individualmente, perguntas sobre as principais áreas da vida a dois. As respostas serão comparadas para identificar necessidades, diferenças, expectativas e aquilo que cada um deseja mudar.",
    "Depois, essas respostas serão transformadas em decisões, compromissos e cláusulas personalizadas para o casamento de vocês.",
    "Se falta intimidade, vocês poderão criar acordos para aumentar os momentos a dois. Se existe sobrecarga com casa, filhos e responsabilidades, poderão equilibrar melhor as tarefas. Se falta carinho ou atenção, o contrato poderá trazer atitudes concretas de aproximação. Se o problema está na comunicação, poderão definir formas melhores de conversar.",
    "O seu Contrato de Casamento será construído a partir daquilo que vocês vivem, sentem falta e desejam mudar.",
    "Ao final, vocês receberão o manual personalizado do próprio casamento: um contrato para ler juntos, revisar e seguir os compromissos que escolheram assumir.",
    "O Contrato de Casamento foi criado para ajudar vocês a decidir como desejam viver daqui para frente.",
  ],
  PRECISA_MELHORAR: [
    "Esse resultado mostra que o relacionamento de vocês possui pontos positivos, mas várias áreas importantes ainda precisam de atenção.",
    "Não significa que o casamento esteja ruim em tudo. Existem coisas que funcionam, momentos bons e uma base que pode ser fortalecida.",
    "Mas também existem necessidades que ainda não estão sendo atendidas como deveriam.",
    "Talvez exista carinho, mas poderia existir mais. Vocês conversam, mas alguns assuntos ainda ficam mal resolvidos. Existe intimidade, mas pode faltar frequência, iniciativa ou conexão. Vocês conseguem viver juntos, mas a rotina pode estar ocupando espaço demais.",
    "A seguir, veja com atenção a nota de cada uma das 10 áreas.",
    "É ali que você vai entender onde o relacionamento está mais forte e onde existem sinais de que algo precisa mudar.",
    "O Método Contrato de Casamento vai aprofundar essas áreas.",
    "Vocês irão responder, individualmente, perguntas mais completas para identificar necessidades, diferenças, expectativas e aquilo que cada um gostaria de viver de uma maneira melhor.",
    "Essas respostas serão transformadas em conversas, decisões, compromissos e cláusulas personalizadas para vocês.",
    "Porque um casamento que está “mais ou menos” não precisa permanecer assim.",
    "Talvez vocês não precisem reconstruir tudo.",
    "Talvez precisem apenas entender melhor o que está faltando, ajustar aquilo que não está funcionando e fortalecer tudo aquilo que ainda existe de bom.",
    "Ao final, vocês receberão o manual personalizado do próprio casamento, criado a partir da realidade de vocês, para ler juntos, revisar e colocar em prática.",
    "Esta pode ser a oportunidade de transformar uma relação que hoje está apenas funcionando em um casamento mais próximo, mais consciente e muito mais satisfatório para os dois.",
  ],
  ESTA_BOM: [
    "Esse é um resultado muito positivo.",
    "De modo geral, suas respostas mostram que o relacionamento de vocês possui uma base forte e que várias áreas importantes da vida a dois estão funcionando muito bem.",
    "Existe carinho. Existe diálogo. Existe conexão. Existe disposição para caminhar juntos.",
    "Isso merece ser reconhecido e valorizado.",
    "Mas cada relacionamento é formado por várias áreas diferentes.",
    "Por isso, logo abaixo você poderá conhecer a nota individual de cada um dos 10 tópicos e entender com mais clareza quais são os maiores pontos fortes do casamento de vocês e onde ainda existe espaço para melhorar.",
    "Mesmo em um relacionamento com uma excelente nota geral, uma área específica pode precisar de mais atenção.",
    "E aquilo que já está funcionando bem também precisa ser cuidado para continuar assim.",
    "O objetivo não é procurar problemas onde eles não existem.",
    "É descobrir o que vocês estão fazendo certo, o que precisa ser preservado e o que ainda pode deixar o relacionamento melhor.",
    "É exatamente aí que entra o Método Contrato de Casamento.",
    "No método completo, você e seu cônjuge irão responder, individualmente, perguntas mais profundas sobre as principais áreas da vida a dois.",
    "As respostas vão mostrar aquilo que vocês já fazem bem, pequenas diferenças que talvez nunca tenham sido conversadas e desejos que ainda podem ser transformados em decisões.",
    "Se o carinho está bom, vocês poderão identificar quais atitudes fazem cada um se sentir amado e preservar isso.",
    "Se a vida íntima está satisfatória, poderão conversar sobre aquilo que desejam continuar vivendo e como proteger esse espaço do casal.",
    "Se as responsabilidades estão equilibradas, poderão deixar mais claro aquilo que já funciona para evitar que a rotina futura gere sobrecarga.",
    "Se a comunicação é boa, poderão construir acordos para preservar essa qualidade mesmo nos momentos difíceis.",
    "Ao final, vocês receberão o Contrato de Casamento personalizado de vocês.",
    "Um verdadeiro manual do relacionamento, construído a partir da realidade do casal, com decisões, compromissos e cláusulas escolhidas pelos dois.",
    "Um documento para ler juntos, revisar ao longo da vida e lembrar não apenas aquilo que precisa mudar, mas também tudo aquilo que vocês escolheram continuar fazendo para proteger o casamento.",
    "Uma nota alta mostra que vocês já construíram muita coisa boa.",
    "O Contrato de Casamento pode ajudar vocês a entender por que isso funciona, preservar essa base e continuar construindo uma relação ainda mais forte, consciente e feliz.",
  ],
};

export const AREA_PRELIMINARY_ANALYSIS: Record<string, Record<ScorePresentationStatus, string[]>> = {
  afeto_valorizacao: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que existe uma falta importante de carinho e valorização na sua relação. Está faltando aquilo que, no dia a dia, faz você se sentir amado(a) e importante: atenção, proximidade, palavras de reconhecimento, gestos de carinho e atitudes de cuidado.",
      "Vamos ajudar seu cônjuge a entender algo muito simples: você não está pedindo demais. Você só quer se sentir mais amado(a), desejado(a) e valorizado(a) dentro da sua relação.",
      "Imagine chegar em casa e, sem precisar pedir, receber um abraço, um toque de carinho, uma palavra de afeto, atenção e aquele cuidado especial que faz você se sentir amado(a) e valorizado(a).",
      "Imagine poder conversar sobre aquilo que está faltando sem transformar tudo em cobrança, discussão ou silêncio.",
      "Se é esse tipo de relacionamento que você deseja construir, existe um próximo passo.",
      "No Contrato de Casamento, você e seu cônjuge irão responder, individualmente, perguntas sobre esse e outros pontos importantes da vida a dois.",
      "O objetivo é transformar sentimentos, necessidades e expectativas que muitas vezes nunca foram claramente conversadas em decisões práticas e compromissos construídos pelos dois.",
      "E ao final, vocês receberão o próprio Contrato de Casamento do casal — um verdadeiro manual do relacionamento, construído a partir das respostas, conversas e decisões de vocês.",
      "Um documento personalizado para ler juntos, revisar ao longo do relacionamento e lembrar os compromissos que vocês escolheram assumir um com o outro.",
      "Porque muitas vezes o problema não é a ausência de amor.",
      "É nunca ter conseguido conversar com clareza sobre como cada um precisa ser amado, cuidado e valorizado.",
      "Esta é a oportunidade de transformar aquilo que hoje está fazendo falta em uma conversa que finalmente precisa acontecer entre vocês para mudar seu casamento.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que existe carinho e valorização na relação, mas ainda não na intensidade ou frequência que poderiam existir.",
      "Há momentos em que você se sente amado(a), reconhecido(a) e importante. Mas provavelmente também existem momentos em que sente falta de mais atenção, proximidade, carinho ou demonstrações de afeto.",
      "Vamos ajudar seu cônjuge a entender melhor aquilo que faz você se sentir amado(a).",
      "Imagine receber mais espontaneamente um abraço, uma palavra carinhosa, um elogio, um cuidado ou aquela atenção que demonstra: “você continua sendo importante para mim”.",
      "Não é preciso ignorar aquilo que já existe de bom.",
      "É preciso fazer o que já funciona acontecer mais vezes.",
      "No Contrato de Casamento, vocês poderão identificar quais demonstrações de carinho são mais importantes para cada um e transformar isso em atitudes concretas.",
      "Mais atenção. Mais reconhecimento. Mais proximidade. Mais momentos de afeto.",
      "Esta é a oportunidade de pegar um carinho que já existe e torná-lo mais presente, percebido e valorizado dentro da relação.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, carinho, afeto e valorização são pontos fortes na relação de vocês.",
      "Você percebe atenção, proximidade e demonstrações que fazem você se sentir amado(a), importante e valorizado(a).",
      "Isso é muito positivo.",
      "Significa que, no dia a dia, existem atitudes que ajudam a manter a conexão entre vocês: um abraço, uma palavra de carinho, reconhecimento, cuidado, interesse e presença.",
      "Essas pequenas demonstrações parecem simples, mas fazem uma enorme diferença dentro de um casamento.",
      "Quando uma pessoa se sente amada e valorizada, normalmente existe mais abertura para conversar, mais segurança emocional e mais vontade de permanecer próxima.",
      "O objetivo agora não é procurar um problema onde as respostas mostram que as coisas estão funcionando bem.",
      "É preservar aquilo que vocês já construíram e continuar fortalecendo essa área.",
      "No Contrato de Casamento, vocês também poderão registrar aquilo que faz bem para cada um: formas de demonstrar carinho, atitudes que desejam preservar e pequenos compromissos para não permitir que a rotina faça desaparecer algo que hoje é especial.",
      "Porque um relacionamento saudável não é apenas aquele que corrige o que está errado.",
      "É também aquele que reconhece o que está dando certo e escolhe continuar cuidando.",
    ],
  },
  comunicacao: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a comunicação entre vocês está muito abaixo do que deveria estar.",
      "Está faltando mais diálogo, mais abertura para falar sobre o que incomoda, mais liberdade para expressar necessidades e mais disposição para ouvir e compreender um ao outro.",
      "Você deseja viver um casamento em que possa falar e sentir que realmente foi ouvido(a).",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você não quer apenas “conversar mais”. Quer conseguir dizer o que sente, explicar o que precisa e falar sobre aquilo que está incomodando sem tudo terminar em discussão, silêncio, ironia ou afastamento.",
      "Imagine conseguir sentar com seu cônjuge e conversar com calma sobre algo importante.",
      "Falar sem precisar gritar. Ouvir sem interromper. Perguntar antes de tirar conclusões. Explicar aquilo que machucou. E terminar uma conversa sentindo que, mesmo pensando diferente, vocês conseguiram se entender melhor.",
      "Está faltando esse espaço entre vocês.",
      "Pode existir dificuldade para falar sobre sentimentos, medo da reação do outro, mágoas acumuladas, impaciência, respostas agressivas, silêncio ou o hábito de evitar assuntos importantes.",
      "No Contrato de Casamento, você e seu cônjuge irão responder, individualmente, perguntas sobre diálogo, escuta, necessidades, conflitos, silêncio, críticas, interrupções e aquilo que cada um sente que precisa mudar na comunicação.",
      "Essas respostas vão ajudar vocês a entender onde a conversa está falhando e o que cada um precisa fazer diferente.",
      "Falar com mais clareza. Ouvir até o outro terminar. Expressar necessidades sem atacar. Não fugir das conversas importantes. Criar momentos para conversar e buscar soluções juntos.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para melhorar a forma de conversar, resolver os problemas e não deixar aquilo que precisa ser dito virar mágoa, distância ou silêncio.",
      "Esta é a oportunidade de transformar discussões, mal-entendidos e silêncio em diálogo, compreensão e decisões construídas pelos dois.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que vocês conseguem conversar, mas a comunicação ainda não funciona tão bem em todos os momentos.",
      "Existem assuntos que vocês resolvem com tranquilidade, mas outros podem terminar em silêncio, impaciência, mal-entendidos, discussão ou simplesmente ficar sem solução.",
      "Vocês já possuem uma base de diálogo.",
      "Agora precisam melhorar a qualidade das conversas mais difíceis.",
      "Imagine conseguir falar sobre aquilo que incomoda sem precisar guardar tudo até explodir.",
      "Imagine explicar uma necessidade e sentir que o outro realmente procurou compreender.",
      "No Contrato de Casamento, vocês irão aprofundar questões sobre diálogo, escuta, críticas, interrupções, silêncio, conflitos e necessidades.",
      "As respostas vão mostrar onde a comunicação já funciona e onde precisa melhorar.",
      "Ouvir mais. Interromper menos. Falar com clareza. Escolher melhor o momento. Não fugir das conversas importantes. Voltar ao assunto quando algo não estiver resolvido.",
      "O objetivo é transformar uma comunicação que hoje funciona apenas em algumas situações em uma ferramenta cada vez mais segura para o relacionamento.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, a comunicação entre vocês está funcionando muito bem.",
      "Existe espaço para conversar, expressar sentimentos, explicar necessidades e procurar compreender o ponto de vista do outro.",
      "Isso é uma grande força dentro do relacionamento.",
      "Conseguir falar sobre aquilo que incomoda sem transformar tudo em discussão, ouvir até o outro terminar e buscar soluções juntos protege muitas outras áreas do casamento.",
      "Vocês parecem ter construído uma base importante: a possibilidade de conversar.",
      "E isso merece ser preservado.",
      "Mesmo casais que se comunicam bem podem enfrentar assuntos mais difíceis, fases de estresse ou momentos em que será necessário ter ainda mais cuidado com as palavras e com a forma de ouvir.",
      "No Contrato de Casamento, vocês poderão identificar aquilo que já funciona na comunicação e transformar essas boas práticas em acordos para o futuro.",
      "Como conversar em momentos difíceis. Como retomar um assunto. Como pedir algo sem atacar. Como ouvir sem se defender imediatamente.",
      "A ideia não é mudar uma comunicação que está boa.",
      "É proteger aquilo que vocês já fazem bem e criar ferramentas para continuar se entendendo mesmo quando surgirem assuntos difíceis.",
    ],
  },
  intimidade: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a vida sexual e a intimidade de vocês estão muito abaixo do que deveriam estar.",
      "Está faltando mais proximidade, mais desejo, mais iniciativa e mais momentos íntimos entre vocês.",
      "Você deseja viver um casamento com uma intimidade mais presente, prazerosa e satisfatória.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você não quer apenas “fazer mais sexo”. Quer sentir desejo entre vocês, perceber iniciativa, interesse, aproximação e vontade de estar junto.",
      "Imagine seu cônjuge separar um momento só para vocês: uma massagem prazerosa, um carinho mais demorado, um abraço que não termina rápido, um convite para ficarem juntos sem celular, sem pressa e sem outras preocupações.",
      "Imagine também sentir liberdade para procurar seu cônjuge, demonstrar desejo e conversar sobre intimidade sem medo de rejeição, constrangimento ou discussão.",
      "Está faltando tempo a dois. Está faltando espaço para vocês se aproximarem e cuidarem dessa parte do casamento.",
      "Pode existir cansaço, estresse, mágoas, problemas de saúde, diferenças de desejo, rotina pesada, falta de iniciativa ou distância emocional.",
      "No Contrato de Casamento, você e seu cônjuge irão responder, individualmente, perguntas sobre frequência sexual, desejo, iniciativa, satisfação, dificuldades, preferências, limites e aquilo que cada um sente que está faltando.",
      "Essas respostas vão ajudar vocês a entender com mais clareza o que está afastando o casal e o que precisa mudar.",
      "Criar mais tempo a dois. Conversar sobre frequência. Buscar mais aproximação. Ter mais iniciativa. Criar momentos de carinho e intimidade durante a semana.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para aumentar os encontros íntimos toda semana e não deixar a vida sexual continuar ruim.",
      "Esta é a oportunidade de transformar frustração em conversa, decisão e atitude e começar a construir uma vida íntima mais presente, desejada e prazerosa para os dois.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que existe vida íntima entre vocês, mas ela ainda pode ser muito melhor.",
      "Há desejo, aproximação ou momentos satisfatórios, porém alguma coisa ainda está faltando para que essa área seja realmente completa para você.",
      "Pode ser frequência. Mais iniciativa. Mais tempo a dois. Mais carinho. Mais liberdade para demonstrar desejo ou conversar sobre aquilo que cada um gosta e precisa.",
      "Imagine vocês criando mais espaço para a intimidade durante a semana.",
      "Um carinho mais demorado. Uma massagem. Um convite inesperado. Mais iniciativa. Mais liberdade para procurar o outro e demonstrar desejo.",
      "No Contrato de Casamento, vocês irão conversar com mais profundidade sobre frequência sexual, satisfação, iniciativa, preferências, dificuldades e aquilo que cada um gostaria que fosse diferente.",
      "As respostas poderão ser transformadas em compromissos reais para cuidar dessa área.",
      "Não significa que a vida sexual de vocês esteja ruim.",
      "Significa que existe espaço para torná-la mais presente, prazerosa, desejada e satisfatória para os dois.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, a vida sexual e a intimidade de vocês estão em um nível muito positivo.",
      "Existe desejo, aproximação, satisfação e espaço para viver a intimidade como uma parte importante do casamento.",
      "Isso merece ser valorizado.",
      "Sentir-se desejado(a), ter liberdade para procurar o outro, demonstrar interesse e compartilhar momentos íntimos ajuda a manter o casal conectado para além das responsabilidades do dia a dia.",
      "Uma vida íntima saudável também precisa continuar recebendo atenção.",
      "Rotina, trabalho, filhos, cansaço e mudanças ao longo da vida podem alterar frequência, desejo e disponibilidade.",
      "Por isso, o objetivo não é simplesmente dizer: “está bom e pronto.”",
      "É preservar aquilo que hoje funciona.",
      "No Contrato de Casamento, vocês poderão conversar sobre frequência, iniciativa, carinho, preferências, momentos a dois e aquilo que cada um considera importante para continuar vivendo uma intimidade prazerosa e satisfatória.",
      "Vocês poderão inclusive registrar atitudes que desejam manter: separar tempo para o casal, cultivar o desejo, criar momentos especiais e continuar conversando com liberdade sobre essa área.",
      "O que hoje é bom também merece cuidado para continuar sendo bom amanhã.",
    ],
  },
  conflitos_reconciliacao: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a forma como vocês lidam com conflitos e reconciliação está muito abaixo do que deveria estar.",
      "As discussões estão deixando marcas. Problemas se repetem, pedidos de desculpas podem não acontecer como deveriam e, muitas vezes, a reconciliação demora ou nem chega de verdade.",
      "Você deseja viver um casamento em que uma briga não vire dias de silêncio, distância, orgulho ou mágoa acumulada.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você não quer um casamento sem divergências. Quer aprender a discordar sem ferir, resolver os problemas sem destruir a relação e conseguir se reconciliar de verdade depois de um conflito.",
      "Imagine poder conversar depois de uma discussão, ouvir um pedido sincero de desculpas, reconhecer também a sua parte e sentir que aquele problema foi realmente encerrado.",
      "Imagine não precisar dormir com raiva, passar dias sem se falar ou voltar sempre às mesmas feridas.",
      "Pode existir orgulho, dificuldade para pedir perdão, impulsividade, palavras duras, silêncio, ressentimento ou problemas antigos que nunca foram resolvidos.",
      "No Contrato de Casamento, você e seu cônjuge irão responder, individualmente, perguntas sobre discussões, pedidos de desculpas, perdão, silêncio, mágoas, problemas recorrentes e reconciliação.",
      "Essas respostas vão ajudar vocês a entender o que piora os conflitos e o que precisa mudar.",
      "Parar uma discussão antes de perder o controle. Voltar a conversar depois. Pedir desculpas quando errar. Não usar o silêncio como punição. Resolver o problema sem atacar a pessoa. Criar um caminho claro para a reconciliação.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para lidar melhor com as divergências e não permitir que uma briga se transforme em dias de distância.",
      "Esta é a oportunidade de transformar conflitos que hoje machucam em conversas que resolvem, aproximam e ajudam vocês a recomeçar juntos.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que vocês conseguem superar alguns conflitos, mas ainda existem discussões ou problemas que poderiam ser resolvidos de uma maneira melhor.",
      "Em alguns momentos vocês conseguem conversar, pedir desculpas e seguir em frente.",
      "Em outros, podem surgir silêncio, orgulho, palavras duras, ressentimento ou assuntos que voltam repetidamente porque nunca foram realmente encerrados.",
      "O objetivo não é viver um casamento sem divergências.",
      "É aprender a passar por elas sem machucar tanto a relação.",
      "Imagine uma discussão terminar com uma conversa verdadeira, um pedido de desculpas e a sensação de que aquele assunto finalmente foi resolvido.",
      "No Contrato de Casamento, vocês irão identificar aquilo que costuma piorar os conflitos e aquilo que ajuda na reconciliação.",
      "Quando parar. Quando voltar a conversar. Como pedir desculpas. O que não deve ser feito durante uma briga. Como resolver o problema sem atacar a pessoa.",
      "Vocês já conseguem superar algumas dificuldades.",
      "Agora podem construir uma forma mais madura e segura de enfrentar aquelas que ainda machucam.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, vocês têm conseguido lidar bem com conflitos e reconciliação.",
      "Isso não significa que vocês nunca discordem.",
      "Significa que existe uma boa capacidade de conversar, reconhecer erros, procurar soluções e voltar a se aproximar depois de momentos difíceis.",
      "Essa é uma qualidade muito importante dentro de um casamento.",
      "Não é a ausência de conflitos que define uma relação saudável.",
      "É a forma como o casal atravessa esses conflitos.",
      "Quando existe espaço para pedir desculpas, perdoar, retomar uma conversa e evitar que uma briga se transforme em dias de distância, o relacionamento fica mais protegido.",
      "No Contrato de Casamento, vocês poderão preservar aquilo que já funciona e deixar ainda mais claro como desejam agir nos momentos de tensão.",
      "Quando interromper uma discussão. Quando voltar a conversar. Como pedir desculpas. O que não deve ser dito durante uma briga. Como buscar reconciliação.",
      "O objetivo é simples:",
      "continuar resolvendo os problemas sem permitir que eles destruam aquilo que vocês construíram juntos.",
    ],
  },
  tempo_conexao_futuro: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que o tempo, a conexão e a perspectiva de futuro entre vocês estão muito abaixo do que deveriam estar.",
      "Está faltando prioridade para a vida a dois. Está faltando mais presença, mais momentos juntos e mais sinais de que o relacionamento continua sendo uma escolha importante para os dois.",
      "Você deseja sentir que ainda existe um “nós”.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você não quer apenas morar junto, dividir contas ou cumprir responsabilidades. Quer sentir que vocês continuam sendo um casal, que existe interesse em estar perto, criar momentos juntos e construir planos para o futuro.",
      "Imagine seu cônjuge separar um tempo só para vocês.",
      "Um jantar. Um passeio. Uma conversa sem celular. Um fim de semana diferente. Um momento para lembrar de vocês dois e não apenas dos problemas, dos filhos, do trabalho e das obrigações.",
      "Imagine também poder conversar sobre o futuro e perceber que os dois ainda desejam caminhar na mesma direção.",
      "Está faltando tempo de qualidade. Está faltando conexão. E essa parte do relacionamento precisa voltar a receber atenção.",
      "Pode existir rotina pesada, trabalho, filhos, cansaço, prioridades diferentes, distanciamento emocional ou simplesmente o hábito de deixar o casal sempre por último.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre tempo juntos, prioridade, conexão, planos, sonhos e expectativas para o futuro.",
      "Essas respostas vão ajudar vocês a entender o que está afastando o casal e o que precisa mudar.",
      "Criar tempo a dois. Planejar momentos juntos. Demonstrar prioridade. Conversar sobre o futuro. Voltar a construir sonhos e decisões como casal.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para não deixar a relação ser consumida apenas pela rotina.",
      "Esta é a oportunidade de voltar a cuidar do “nós” e começar a construir uma relação mais próxima, presente e com futuro.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que ainda existe conexão entre vocês, mas a vida de casal pode estar recebendo menos espaço do que merece.",
      "Existem momentos juntos e provavelmente ainda existem planos, carinho e vontade de permanecer na relação.",
      "Mas rotina, trabalho, filhos, cansaço e responsabilidades podem estar ocupando cada vez mais espaço.",
      "E o “nós” acaba ficando para depois.",
      "Imagine vocês voltando a separar momentos só para o casal.",
      "Um jantar. Um passeio. Uma conversa sem celular. Um programa diferente. Um projeto ou sonho que os dois possam construir juntos.",
      "No Contrato de Casamento, vocês poderão conversar sobre tempo de qualidade, prioridades, momentos a dois, sonhos, projetos e aquilo que desejam para o futuro.",
      "Criar mais tempo juntos. Planejar momentos especiais. Voltar a conversar sobre sonhos. Demonstrar que a relação continua sendo prioridade.",
      "Vocês ainda possuem uma conexão.",
      "O próximo passo é não permitir que a rotina enfraqueça aquilo que ainda existe de bom entre vocês.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, existe uma boa conexão entre vocês e um sentimento positivo de continuidade da relação.",
      "Vocês parecem conseguir preservar aquilo que todo casamento precisa: o “nós”.",
      "Existe espaço para estar juntos, compartilhar momentos, demonstrar prioridade e imaginar o futuro como casal.",
      "Isso é muito positivo.",
      "Porque um relacionamento pode facilmente ser consumido por trabalho, filhos, contas, rotina e responsabilidades.",
      "Quando o casal consegue continuar criando momentos próprios, conversando sobre sonhos e demonstrando que a relação permanece importante, existe uma base muito valiosa para o futuro.",
      "No Contrato de Casamento, vocês poderão registrar aquilo que desejam continuar construindo juntos.",
      "Momentos a dois. Viagens. Projetos. Sonhos. Planos familiares. Tempo de qualidade. Decisões para o futuro.",
      "Não porque essa área esteja ruim.",
      "Mas porque aquilo que é importante também precisa ser protegido.",
      "O objetivo é continuar construindo uma história em que, mesmo com todas as responsabilidades da vida, vocês não deixem de escolher um ao outro.",
    ],
  },
  autopercepcao_disposicao: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a forma como você percebe sua própria participação nas mudanças ainda precisa melhorar.",
      "Está faltando olhar com mais clareza para aquilo que também depende de você.",
      "É natural enxergar primeiro o que o outro faz de errado. Mas um relacionamento começa a mudar de verdade quando os dois conseguem reconhecer sua parte e decidir fazer diferente.",
      "Vamos ajudar vocês a entender isso.",
      "Você não precisa assumir toda a culpa pelos problemas da relação. Mas também não pode colocar toda a responsabilidade da mudança nas mãos do seu cônjuge.",
      "Imagine os dois conseguindo dizer:",
      "“Eu entendo o que está te incomodando. Vou olhar para a minha parte e também vou mudar algumas coisas.”",
      "Isso muda completamente uma conversa.",
      "Pode existir diferença entre a forma como você enxerga o relacionamento e a forma como seu cônjuge enxerga. Aquilo que para um parece pequeno pode estar machucando muito o outro.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre responsabilidade, disposição para mudar, reconhecimento dos próprios erros, esforço, expectativas e diferenças na forma como cada um percebe a relação.",
      "Essas respostas vão ajudar vocês a comparar as duas visões e entender onde cada um precisa avançar.",
      "Reconhecer a própria parte. Ouvir sem se defender o tempo todo. Aceitar ajustes. Mudar atitudes. Cumprir aquilo que foi combinado. Demonstrar, na prática, disposição para melhorar.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para que a mudança não fique apenas na cobrança do outro.",
      "Esta é a oportunidade de sair do “você precisa mudar” e começar a construir o “o que nós dois podemos fazer para melhorar nosso casamento?”",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que existe alguma disposição para reconhecer erros e mudar, mas ainda há espaço para olhar com mais clareza para a própria participação no relacionamento.",
      "Em alguns momentos você consegue perceber aquilo que pode fazer diferente.",
      "Em outros, pode ser mais fácil enxergar primeiro aquilo que seu cônjuge precisa mudar.",
      "Isso é comum.",
      "Mas um casamento melhora mais rápido quando os dois conseguem dizer:",
      "“Eu também tenho uma parte nisso e estou disposto(a) a fazer diferente.”",
      "No Contrato de Casamento, vocês irão responder separadamente sobre responsabilidade, esforço, mudanças, expectativas e a forma como cada um percebe a relação.",
      "Depois, será possível comparar essas duas visões.",
      "Talvez você descubra que algo que considera pequeno é muito importante para seu cônjuge — e o contrário também.",
      "Reconhecer. Ouvir. Ajustar. Cumprir aquilo que foi combinado.",
      "Vocês já possuem alguma disposição para mudar.",
      "Agora precisam transformar essa disposição em atitudes mais claras e constantes.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que suas respostas revelam uma boa capacidade de olhar também para a sua própria participação no relacionamento.",
      "Isso é muito importante.",
      "Você parece compreender que melhorar um casamento não significa apenas apontar aquilo que o outro precisa mudar.",
      "Também envolve reconhecer os próprios erros, ouvir, fazer ajustes e assumir responsabilidade pelas próprias atitudes.",
      "Essa disposição cria espaço para mudanças reais.",
      "Porque quando os dois conseguem dizer “eu também posso melhorar nisso”, muitas conversas deixam de ser uma disputa para descobrir quem está errado e passam a ser uma busca por solução.",
      "No Contrato de Casamento, essa disposição poderá ser transformada em compromissos concretos.",
      "Cada um poderá identificar aquilo que deseja preservar, aquilo em que pode melhorar e quais atitudes está disposto a assumir para contribuir com a relação.",
      "Mesmo quando essa área apresenta uma nota alta, sempre existe espaço para amadurecer.",
      "O mais importante é que existe uma base muito positiva:",
      "a disposição para olhar para si e participar da mudança.",
    ],
  },
  dinheiro_casal: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a forma como vocês lidam com o dinheiro precisa melhorar.",
      "Está faltando mais diálogo, transparência e organização sobre aquilo que entra, aquilo que sai e sobre as decisões financeiras do casal.",
      "Dinheiro não é apenas conta para pagar. Ele envolve escolhas, prioridades, segurança, sonhos, preocupações e também pode se transformar em uma das maiores fontes de conflito dentro do relacionamento.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você deseja poder conversar sobre dinheiro sem medo, cobrança, esconderijos ou discussões.",
      "Quer saber o que vocês ganham, como estão gastando, quais são as prioridades, quais compromissos existem e para onde vocês desejam caminhar juntos.",
      "Imagine os dois conseguindo sentar e conversar com clareza sobre gastos, dívidas, compras, economia, investimentos e planos para o futuro.",
      "Imagine não descobrir uma despesa importante depois que ela já aconteceu.",
      "Pode existir diferença na forma como cada um gasta, economiza, ajuda familiares, usa cartão, assume dívidas ou entende aquilo que é prioridade.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre renda, gastos, dívidas, compras, contas, reservas, planejamento, prioridades e decisões financeiras.",
      "Essas respostas vão ajudar vocês a entender onde estão as diferenças e o que precisa mudar.",
      "Conversar antes de decisões importantes. Definir prioridades. Organizar despesas. Criar limites. Planejar juntos. Evitar segredos financeiros e estabelecer objetivos para o dinheiro do casal.",
      "E, no Contrato de Casamento, os dois vão construir compromissos reais para que o dinheiro deixe de ser motivo de insegurança e passe a ser administrado com mais clareza, responsabilidade e união.",
      "Esta é a oportunidade de transformar preocupação financeira em conversa, planejamento e decisões construídas pelos dois.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que vocês conseguem lidar com dinheiro em vários momentos, mas ainda existem questões financeiras que podem ser melhor organizadas e conversadas.",
      "Talvez vocês concordem sobre algumas prioridades, mas tenham diferenças em relação a gastos, compras, economia, dívidas, cartão, ajuda a familiares ou planejamento.",
      "Isso não significa necessariamente que exista um grande problema financeiro.",
      "Significa que algumas decisões ainda precisam de mais clareza e alinhamento.",
      "Imagine os dois sabendo exatamente quais são as prioridades e conseguindo conversar sobre dinheiro sem transformar tudo em cobrança ou discussão.",
      "No Contrato de Casamento, vocês irão aprofundar assuntos como renda, gastos, compras, dívidas, reservas, planejamento, prioridades e objetivos financeiros.",
      "Vocês poderão definir limites, organizar despesas e decidir juntos aquilo que merece prioridade.",
      "Uma vida financeira razoavelmente organizada pode se tornar muito mais tranquila quando o casal deixa de apenas administrar problemas e começa a planejar o futuro em conjunto.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, vocês estão lidando bem com dinheiro dentro da relação.",
      "Existe diálogo, organização e um bom nível de entendimento sobre gastos, prioridades e decisões financeiras.",
      "Isso é muito positivo.",
      "Dinheiro pode ser uma das maiores fontes de conflito dentro de um relacionamento quando existem segredos, decisões isoladas ou prioridades completamente diferentes.",
      "Quando o casal consegue conversar com clareza sobre aquilo que entra, aquilo que sai e aquilo que deseja construir, o dinheiro deixa de ser apenas motivo de preocupação e passa a fazer parte do planejamento da vida dos dois.",
      "No Contrato de Casamento, vocês poderão preservar essa boa organização e deixar ainda mais claros alguns acordos.",
      "Como lidar com compras importantes. Reservas. Dívidas. Investimentos. Ajuda a familiares. Objetivos financeiros e projetos para o futuro.",
      "A intenção não é criar regras desnecessárias onde existe confiança.",
      "É transformar o entendimento que vocês já possuem em decisões claras que possam continuar protegendo a relação.",
    ],
  },
  casa_filhos_responsabilidades: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a divisão das responsabilidades da casa, dos filhos e da família está muito abaixo do que deveria estar.",
      "Está faltando mais equilíbrio, mais participação e mais clareza sobre aquilo que cada um precisa assumir no dia a dia.",
      "Você não quer sentir que precisa lembrar, pedir ou cobrar tudo o tempo todo.",
      "Quer perceber que seu cônjuge também enxerga o que precisa ser feito, assume responsabilidades e participa de verdade da organização da casa e da família.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Imagine não precisar carregar sozinho(a) a preocupação com limpeza, comida, compras, contas, escola, compromissos dos filhos e tantas outras tarefas da rotina.",
      "Imagine os dois sabendo o que cada um precisa fazer e dividindo essas responsabilidades de uma forma mais justa.",
      "Porque quando as responsabilidades ficam mais equilibradas, também sobra mais tempo e energia para o relacionamento.",
      "Menos cansaço. Menos cobrança. Mais disposição para conversar, sair juntos, demonstrar carinho, ter momentos a dois e cuidar da intimidade.",
      "Muitas vezes, o problema não está apenas na falta de afeto ou de desejo. Existe alguém cansado, sobrecarregado e sem espaço emocional para viver outras partes do casamento.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre tarefas domésticas, filhos, compromissos da família, organização e responsabilidades.",
      "Essas respostas vão ajudar vocês a entender onde existe sobrecarga e o que precisa mudar.",
      "Dividir tarefas. Definir responsabilidades. Organizar a rotina. Compartilhar os cuidados com os filhos. Evitar que apenas um precise lembrar e cobrar tudo.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para tornar a rotina mais equilibrada e liberar mais tempo e energia para cuidar também do casal.",
      "Esta é a oportunidade de transformar cansaço e cobrança em parceria, organização, carinho, conexão e mais qualidade de vida dentro do casamento.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que existe participação dos dois, mas a divisão das responsabilidades ainda pode ser mais equilibrada.",
      "Algumas tarefas provavelmente estão funcionando bem.",
      "Outras podem estar pesando mais para um dos dois.",
      "E quando alguém começa a ficar cansado, sobrecarregado ou com a sensação de que precisa pedir e lembrar tudo, isso acaba atingindo outras partes do relacionamento.",
      "Menos energia para conversar.",
      "Menos disposição para carinho.",
      "Menos tempo a dois.",
      "Menos vontade para intimidade.",
      "No Contrato de Casamento, vocês poderão identificar como estão divididas as tarefas domésticas, os cuidados com os filhos, compromissos familiares e outras responsabilidades.",
      "Depois, poderão ajustar aquilo que estiver desequilibrado.",
      "Dividir melhor. Organizar a rotina. Definir responsabilidades. Compartilhar decisões.",
      "Não é necessário que tudo seja dividido exatamente pela metade.",
      "O importante é que a divisão pareça justa para os dois e ajude a liberar mais tempo e energia para cuidar também do casamento.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, existe um bom equilíbrio na divisão das responsabilidades da casa e da família.",
      "Você percebe participação, colaboração e uma divisão que parece justa para a realidade de vocês.",
      "Isso é muito importante.",
      "Quando as responsabilidades são compartilhadas de maneira saudável, existe menos sobrecarga, menos cobrança e mais energia disponível para outras partes do relacionamento.",
      "Sobra mais disposição para conversar.",
      "Mais tempo para estar juntos.",
      "Mais espaço para carinho, descanso, intimidade e momentos em família.",
      "No Contrato de Casamento, vocês poderão preservar aquilo que já funciona e deixar ainda mais claras as responsabilidades que cada um deseja continuar assumindo.",
      "Tarefas domésticas. Filhos. Compras. Contas. Compromissos familiares. Organização da rotina.",
      "Isso também ajuda quando surgem mudanças: um novo trabalho, filhos crescendo, alterações de horário ou fases em que um dos dois precisa de mais ajuda.",
      "A boa divisão que existe hoje pode se transformar em uma base ainda mais sólida de parceria para o futuro.",
    ],
  },
  confianca_fidelidade_limites: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que a confiança, a segurança e os limites dentro da relação precisam melhorar.",
      "Está faltando mais clareza sobre aquilo que cada um considera respeito, fidelidade e comportamento adequado dentro do casamento.",
      "Você deseja viver uma relação em que não precise conviver com dúvidas, insegurança ou situações que fazem você se perguntar até onde o outro pode ir.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Você quer sentir segurança. Quer saber que os limites do relacionamento estão claros e que aquilo que foi combinado será respeitado pelos dois.",
      "Imagine poder conversar abertamente sobre amizades, mensagens, redes sociais, pessoas do passado, flertes, conversas privadas e outras situações que podem gerar desconforto.",
      "Imagine os dois conseguindo dizer com clareza:",
      "“Para mim, isso ultrapassa um limite.”",
      "E o outro conseguir compreender e respeitar essa necessidade sem transformar tudo em acusação, ciúme ou discussão.",
      "Pode existir diferença na forma como cada um entende fidelidade, privacidade, amizade, exposição nas redes sociais e proximidade com terceiros.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre confiança, fidelidade, ciúmes, redes sociais, terceiros, privacidade, comportamentos que incomodam e limites importantes para cada um.",
      "Essas respostas vão ajudar vocês a identificar onde existem diferenças e o que precisa ser combinado com mais clareza.",
      "Definir limites. Evitar situações que geram insegurança. Respeitar acordos. Conversar antes de ultrapassar fronteiras importantes. Proteger a relação sem transformar confiança em vigilância.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para aumentar a segurança, reduzir dúvidas e proteger a confiança construída entre vocês.",
      "Esta é a oportunidade de transformar insegurança em clareza, respeito e confiança.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que existe confiança entre vocês, mas algumas situações ainda podem gerar dúvidas, desconforto ou insegurança.",
      "A base não parece estar completamente comprometida.",
      "Mas talvez existam limites que nunca foram claramente conversados.",
      "Amizades. Redes sociais. Mensagens. Pessoas do passado. Privacidade. Flertes. Proximidade com terceiros.",
      "Aquilo que parece normal para um pode incomodar profundamente o outro.",
      "No Contrato de Casamento, vocês poderão descobrir onde essas percepções são diferentes e estabelecer limites compreendidos pelos dois.",
      "Não para transformar o casamento em vigilância.",
      "Mas para que cada um saiba aquilo que protege ou ameaça a segurança emocional do outro.",
      "Conversar. Definir limites. Respeitar acordos. Evitar situações desnecessárias de insegurança.",
      "Vocês já possuem uma base de confiança.",
      "O objetivo é fortalecer essa base e retirar da relação aquelas dúvidas que podem crescer quando nunca são conversadas.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, existe um nível muito positivo de confiança e segurança dentro da relação.",
      "Você percebe respeito, fidelidade e tranquilidade em relação aos limites do casamento.",
      "Isso é uma grande força.",
      "Viver uma relação sem precisar conviver constantemente com dúvidas, suspeitas ou insegurança permite que o casal tenha mais liberdade, proximidade e paz.",
      "Mas confiança também precisa continuar sendo cuidada.",
      "No Contrato de Casamento, vocês poderão conversar sobre aquilo que cada um considera importante preservar em relação a amizades, terceiros, redes sociais, privacidade e comportamentos que poderiam gerar desconforto.",
      "Não para criar vigilância.",
      "Mas para manter claros os limites que ajudam vocês a se sentirem seguros dentro da relação.",
      "Quando os dois sabem aquilo que é importante para o outro e escolhem respeitar esses limites, a confiança deixa de depender apenas de expectativas silenciosas.",
      "Ela passa a ser também resultado de decisões conscientes dos dois.",
    ],
  },
  habitos_compulsoes: {
    PRECISA_MUDAR_COM_URGENCIA: [
      "Esse resultado mostra que existem hábitos ou comportamentos repetitivos que estão trazendo desgaste para o relacionamento ou para a família.",
      "Está faltando mais equilíbrio, mais controle e mais atenção ao impacto que essas atitudes estão causando no dia a dia de vocês.",
      "Quando um hábito começa a ocupar tempo demais, consumir dinheiro, afastar o casal, gerar discussões ou prejudicar responsabilidades, ele deixa de ser apenas uma escolha pessoal e passa a afetar o relacionamento.",
      "Vamos ajudar seu cônjuge a entender isso.",
      "Pode ser excesso de celular, redes sociais, jogos, compras, apostas, trabalho, pornografia, bebidas ou qualquer outro comportamento que esteja tomando um espaço maior do que deveria.",
      "Imagine não precisar mais competir com um celular, um jogo, uma tela ou outro hábito para conseguir atenção, presença e tempo de qualidade.",
      "Imagine os dois conseguindo conversar sem acusações sobre aquilo que está passando do limite e decidir juntos o que precisa mudar.",
      "No Contrato de Casamento, vocês irão responder, individualmente, perguntas sobre hábitos, excessos, frequência, dinheiro, tempo, consequências e comportamentos que estão prejudicando a relação.",
      "Essas respostas vão ajudar vocês a entender o que está causando desgaste e quais mudanças precisam acontecer.",
      "Criar limites. Reduzir excessos. Proteger o dinheiro e o tempo da família. Recuperar momentos a dois. Buscar ajuda quando necessário e assumir responsabilidade quando um comportamento estiver saindo do controle.",
      "E, no Contrato de Casamento, os dois vão estabelecer compromissos reais para impedir que hábitos prejudiciais continuem ocupando o espaço que deveria pertencer ao casamento e à família.",
      "Esta é a oportunidade de transformar desgaste em consciência, decisão e mudança — e recuperar tempo, presença e qualidade de vida dentro da relação.",
    ],
    PRECISA_MELHORAR: [
      "Esse resultado mostra que os hábitos do dia a dia ainda estão relativamente equilibrados, mas alguns deles podem estar ocupando mais espaço do que deveriam.",
      "Pode ser celular, redes sociais, trabalho, jogos, compras, bebidas, apostas, pornografia ou qualquer comportamento repetitivo que comece a retirar tempo, dinheiro, presença ou atenção da relação.",
      "Talvez ainda não seja algo que domine o casamento.",
      "Mas já pode estar provocando incômodo ou desgaste.",
      "Imagine não precisar disputar atenção com uma tela, um jogo, o trabalho ou qualquer outro hábito.",
      "No Contrato de Casamento, vocês irão identificar quais comportamentos estão equilibrados e quais precisam de limites.",
      "Reduzir excessos. Proteger o tempo do casal. Organizar gastos. Recuperar momentos em família. Buscar ajuda quando necessário.",
      "O objetivo não é proibir tudo aquilo que cada um gosta.",
      "É encontrar equilíbrio para que nenhum hábito ocupe o espaço que deveria pertencer ao relacionamento, à família e às responsabilidades.",
      "Vocês ainda estão em uma posição em que pequenos ajustes podem fazer uma diferença muito grande.",
    ],
    ESTA_BOM: [
      "Esse resultado mostra que, pelas suas respostas, os hábitos e comportamentos do dia a dia estão relativamente bem equilibrados e não parecem estar causando um desgaste importante na relação.",
      "Isso é muito positivo.",
      "Celular, redes sociais, trabalho, jogos, compras, bebidas, entretenimento e outros hábitos fazem parte da vida, mas precisam ocupar um espaço saudável.",
      "Quando existe equilíbrio, eles não roubam aquilo que pertence ao casal, à família e às responsabilidades.",
      "O objetivo agora é preservar esse equilíbrio.",
      "No Contrato de Casamento, vocês poderão conversar sobre hábitos que desejam manter sob controle e limites que consideram importantes para proteger a relação.",
      "Tempo de tela. Gastos. Trabalho. Lazer. Momentos em família. Tempo a dois.",
      "Não porque exista necessariamente um problema.",
      "Mas porque muitos hábitos começam pequenos e podem ganhar espaço ao longo do tempo sem que o casal perceba.",
      "Ter uma nota alta nessa área é um bom sinal.",
      "E transformar esse equilíbrio em consciência e acordos pode ajudar vocês a continuar protegendo aquilo que hoje está funcionando bem.",
    ],
  },
};

export function getGeneralPreliminaryAnalysis(status: ScorePresentationStatus): string[] {
  return GENERAL_PRELIMINARY_ANALYSIS[status] ?? [];
}

export function getAreaPreliminaryAnalysis(areaKey: string, status: ScorePresentationStatus): string[] {
  return AREA_PRELIMINARY_ANALYSIS[areaKey]?.[status] ?? [];
}

